version: '3.4'

services:
  osx:
    container_name: docker-osx
    build:
      context: .
      args:
        - SIZE=200G
        - VERSION=10.15.5
    image: sickcodes/docker-osx
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /lib/modules:/lib/modules
      - docker-osx_data:/home

volumes:
  docker-osx_data:
    name: docker-osx_data
